name: testcontainers-python
on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/${{ matrix.python-version }}.txt
      - name: Install system requirements
        run: |
          apt-get install -y --no-install-recommends unixodbc-dev # required for pyodbc
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get -qq update
          sudo ACCEPT_EULA=Y apt-get -y install msodbcsql17
      - name: Run checks
        run: |
          flake8
          sphinx-build -nW docs docs/_build/html
          py.test -sv --cov-config .coveragerc --cov-report html:skip-covered --cov-report term:skip-covered --cov=testcontainers --tb=short tests/
          codecov
  deploy:
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-16.04
    steps:
      - name: Deploy to PyPi
        run: echo deploying
